name: Alerta CI - Hola Mundo

on:
  push:
    branches:
      - main  # Se ejecutará cuando haya cambios en la rama main

jobs:
  enviar-alerta:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Ejecutar el programa Hola Mundo
      run: node hola.js

    - name: Enviar notificación a ntfy.sh
      run: |
        curl -d "Se ha hecho push al repositorio en la rama main. 🚀" ntfy.sh/devops-itla
